const NUM_SIDEBAR_DEFAULT = 0,
  NUM_SIDEBAR_SETTINGS = 1,
  NUM_SIDEBAR_CONTACTS = 2,
  NUM_SIDEBAR_CHANNEL = 3,
  NUM_SIDEBAR_GROUP = 4,
  NUM_SIDEBAR_CALL = 5,
  NUM_SIDEBAR_CHAT = 6,
  NUM_SIDEBAR_SHOWCONTACT = 7;

export {
  NUM_SIDEBAR_CHANNEL,
  NUM_SIDEBAR_CONTACTS,
  NUM_SIDEBAR_DEFAULT,
  NUM_SIDEBAR_GROUP,
  NUM_SIDEBAR_SETTINGS,
  NUM_SIDEBAR_CALL,
  NUM_SIDEBAR_CHAT,
  NUM_SIDEBAR_SHOWCONTACT
};
const TEXT_STYLES = {
  1: 'Monolotic',
  2: 'Strike',
  3: 'underline',
  4: 'italic',
  5: 'bold',
  6: 'spoil'
};
export { TEXT_STYLES };
const TYPE_USER = 1,
  TYPE_GROUP = 2,
  TYPE_CHANNEL = 3;
export { TYPE_CHANNEL, TYPE_GROUP, TYPE_USER };
