const NUM_SIDEBAR_DEFAULT = 0,
  NUM_SIDEBAR_SETTINGS = 1,
  NUM_SIDEBAR_CONTACTS = 2,
  NUM_SIDEBAR_CHANNEL = 3,
  NUM_SIDEBAR_GROUP = 4,
  NUM_SIDEBAR_CALL = 5,
  NUM_SIDEBAR_CHAT = 6,
  NUM_SIDEBAR_SHOWCONTACT = 7;

const SETTINGS_NOTIFS_MEN = 1,
  SETTINGS_PRIVACY_MEN = 2,
  SETTINGS_STORAGE_MEN = 3,
  SETTINGS_CHAT_MEN = 4,
  SETTINGS_PRIVATE_INFO = 5;
export { SETTINGS_NOTIFS_MEN, SETTINGS_PRIVACY_MEN, SETTINGS_STORAGE_MEN, SETTINGS_CHAT_MEN ,SETTINGS_PRIVATE_INFO};

export {
  NUM_SIDEBAR_CHANNEL,
  NUM_SIDEBAR_CONTACTS,
  NUM_SIDEBAR_DEFAULT,
  NUM_SIDEBAR_GROUP,
  NUM_SIDEBAR_SETTINGS,
  NUM_SIDEBAR_CALL,
  NUM_SIDEBAR_CHAT,
  NUM_SIDEBAR_SHOWCONTACT
};
const TEXT_STYLES = {
  1: 'Monolotic',
  2: 'strike',
  3: 'underline',
  4: 'italic',
  5: 'bold',
  6: 'spoiler'
};
export { TEXT_STYLES };
const TYPE_USER = 0,
  TYPE_GROUP = 1,
  TYPE_CHANNEL = 2;
export { TYPE_CHANNEL, TYPE_GROUP, TYPE_USER };
